"""
Managed extension_navigateur service (Chrome/Chromium).

V1: deterministic scaffold + zip artifact.
- Push sources to GitHub branch (optional but keeps persistence)
- Provide zip download from backend by re-zipping the canonical file set.
"""

from __future__ import annotations

import io
import json
import logging
import zipfile
from datetime import UTC, datetime
from typing import Any

from config import Settings, get_settings
from db.managed_projects_store import ManagedProjectsStore
from tools.project_deletion import hard_delete_managed_project
from tools.export_github import delete_github_branch, push_vitrine_site_to_github

logger = logging.getLogger(__name__)


class ManagedExtensionError(Exception):
    pass


def _now() -> str:
    return datetime.now(tz=UTC).isoformat()


def _extension_files(prompt: str, slug: str) -> dict[str, str]:
    name = slug.replace("-", " ").title()[:45] or "CyberForge Extension"
    manifest = {
        "manifest_version": 3,
        "name": name,
        "version": "0.1.0",
        "description": (prompt.strip()[:120] or "Extension générée par CyberForge"),
        "action": {
            "default_title": name,
            "default_popup": "popup.html",
        },
        "permissions": ["storage"],
        "background": {"service_worker": "background.js"},
        "icons": {
            "16": "icons/icon16.png",
            "48": "icons/icon48.png",
            "128": "icons/icon128.png",
        },
    }
    popup_html = """<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>CyberForge Extension</title>
    <style>
      body { font-family: system-ui, sans-serif; margin: 0; padding: 12px; width: 320px; }
      .card { border: 1px solid #e5e7eb; border-radius: 10px; padding: 12px; }
      .muted { color: #6b7280; font-size: 12px; }
      button { margin-top: 10px; width: 100%; padding: 10px; border-radius: 10px; border: 0; background: #111827; color: white; cursor: pointer; }
    </style>
  </head>
  <body>
    <div class="card">
      <div><strong>Extension MV3</strong></div>
      <div class="muted">Générée par CyberForge</div>
      <div id="count" style="margin-top:10px">Clicks: …</div>
      <button id="inc">Incrémenter</button>
    </div>
    <script src="popup.js"></script>
  </body>
</html>
"""
    popup_js = """async function getCount() {
  const data = await chrome.storage.local.get({ clickCount: 0 });
  return data.clickCount ?? 0;
}

async function setCount(n) {
  await chrome.storage.local.set({ clickCount: n });
}

async function render() {
  const n = await getCount();
  document.getElementById("count").textContent = `Clicks: ${n}`;
}

document.getElementById("inc").addEventListener("click", async () => {
  const n = (await getCount()) + 1;
  await setCount(n);
  await render();
});

render();
"""
    background_js = """chrome.runtime.onInstalled.addListener(() => {
  console.log("CyberForge extension installed");
});
"""
    readme = f"""# {name}

Generated by CyberForge.

## Install (Chrome)
1. Ouvrir `chrome://extensions`
2. Activer **Mode développeur**
3. **Charger l'extension non empaquetée**
4. Sélectionner le dossier dézippé
"""

    # Tiny placeholder PNGs (1x1) as base64? keep as SVG to avoid binary; Chrome accepts PNG only.
    # We'll embed minimal PNG bytes via base64-decoding at zip time? For now: include svg and omit icons in manifest?
    # Keep icons optional by removing icons if we cannot ship png.
    manifest.pop("icons", None)

    return {
        "manifest.json": json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        "popup.html": popup_html,
        "popup.js": popup_js,
        "background.js": background_js,
        "README.md": readme,
    }


def build_extension_zip(files: dict[str, str]) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for path, content in sorted(files.items()):
            if not path or content is None:
                continue
            z.writestr(path.lstrip("/"), content)
    return buf.getvalue()


async def provision_extension(
    *,
    project_id: str,
    run_id: str,
    prompt: str,
    settings: Settings | None,
    store: ManagedProjectsStore,
) -> None:
    resolved = settings or get_settings()
    st = store
    project = await st.get_project(project_id)
    if not project:
        raise ManagedExtensionError("Projet introuvable.")

    slug = project.github_branch
    github_repo = project.github_repo
    files = _extension_files(prompt, slug)

    await st.update_project(project_id, patch={"status": "building", "error_last": None})

    # Persist sources to GitHub branch (like vitrines)
    await push_vitrine_site_to_github(branch_slug=slug, files=files, settings=resolved, repo=github_repo)

    zip_bytes = build_extension_zip(files)
    await st.update_project(
        project_id,
        patch={
            "title": project.title or slug,
            "prompt_last": prompt,
            "status": "deployed",
            "url_production": None,
            "url_preview": None,
            "artifact_kind": "zip",
            "artifact_filename": f"{slug}.zip",
            "error_last": None,
        },
    )
    await st.finish_run(
        run_id,
        status="succeeded",
        artifacts={"artifact_kind": "zip", "artifact_bytes": len(zip_bytes)},
    )


async def update_extension(
    *,
    project_id: str,
    prompt: str,
    settings: Settings | None,
    store: ManagedProjectsStore,
) -> None:
    st = store
    run = await st.create_run(project_id, action="update")
    await provision_extension(
        project_id=project_id,
        run_id=run.id,
        prompt=prompt,
        settings=settings,
        store=store,
    )


async def hard_delete_extension(
    *,
    project_id: str,
    settings: Settings | None,
    store: ManagedProjectsStore,
) -> dict[str, Any]:
    return await hard_delete_managed_project(
        project_id=project_id,
        settings=settings,
        store=store,
        include_extension_zip=True,
        include_pipeline_projects=True,
    )

