"""
Génération de mots de passe démo — courts et mémorisables (3 mots français).
"""

from __future__ import annotations

import secrets

# Mots courants, faciles à dicter au client (sans accents pour saisie simple).
FRENCH_DEMO_WORDS: tuple[str, ...] = (
    "arbre",
    "avion",
    "bateau",
    "bleu",
    "champ",
    "chat",
    "ciel",
    "cour",
    "danse",
    "dent",
    "fleur",
    "forêt",
    "gateau",
    "jaune",
    "jardin",
    "lune",
    "maison",
    "miel",
    "mont",
    "musee",
    "neige",
    "orange",
    "piano",
    "plage",
    "pomme",
    "porte",
    "riviere",
    "rouge",
    "route",
    "salade",
    "sable",
    "serre",
    "soleil",
    "table",
    "train",
    "vert",
    "vague",
    "velo",
    "vent",
    "ville",
    "violet",
    "voile",
    "voiture",
    "voyage",
    "zeste",
    "zoo",
    "abricot",
    "banc",
    "barque",
    "bulle",
    "camion",
    "cascade",
    "chien",
    "coffre",
    "colline",
    "coquille",
    "cristal",
    "etoile",
    "feuille",
    "foret",
    "grenouille",
    "horizon",
    "ile",
    "jungle",
    "labyrinthe",
    "lentille",
    "lumiere",
    "marche",
    "nuage",
    "ocean",
    "olive",
    "papillon",
    "parc",
    "perle",
    "pierre",
    "pluie",
    "poisson",
    "pont",
    "prairie",
    "radis",
    "rocher",
    "rose",
    "savon",
    "source",
    "tigre",
    "tour",
    "tulipe",
    "vache",
    "vallee",
    "verre",
    "vigne",
)


def generate_demo_password() -> str:
    """Retourne un mot de passe du type soleil-bateau-rouge."""
    picks = [secrets.choice(FRENCH_DEMO_WORDS) for _ in range(3)]
    return "-".join(picks)
