"""Routes HTTP — enregistrement centralisé pour éviter les oublis."""

from fastapi import APIRouter

from api.routes import (
    agents_status,
    clients,
    costs,
    coremind,
    demos,
    health,
    admin_ecommerce,
    managed_application_web,
    managed_ecommerce,
    managed_extensions,
    managed_site_reservation,
    managed_vitrines,
    notifications,
    pipeline_artifacts,
    pipeline_stream,
    projects,
    public_demos,
    public_ecommerce,
    public_reservation,
    secrets,
    settings_profile,
    system,
    vitrine,
    vitrine_auth,
)

# (router, prefix OpenAPI)
API_ROUTERS: list[tuple[APIRouter, str]] = [
    (health.router, "/api"),
    (agents_status.router, "/api"),
    (coremind.router, "/api"),
    (pipeline_stream.router, "/api"),
    (pipeline_artifacts.router, "/api"),
    (projects.router, "/api"),
    (costs.router, "/api"),
    (admin_ecommerce.router, "/api"),
    (managed_application_web.router, "/api"),
    (managed_vitrines.router, "/api"),
    (managed_extensions.router, "/api"),
    (managed_site_reservation.router, "/api"),
    (managed_ecommerce.router, "/api"),
    (clients.router, "/api"),
    (secrets.router, "/api"),
    (settings_profile.router, "/api"),
    (system.router, "/api"),
    (demos.router, "/api"),
    (notifications.router, "/api"),
    (vitrine.router, "/api"),
    (vitrine_auth.router, "/api"),
    (public_demos.router, "/api/public"),
    (public_reservation.router, "/api/public"),
    (public_ecommerce.router, "/api/public"),
]

__all__ = [
    "API_ROUTERS",
    "agents_status",
    "clients",
    "costs",
    "coremind",
    "demos",
    "health",
    "admin_ecommerce",
    "managed_application_web",
    "managed_ecommerce",
    "managed_extensions",
    "managed_site_reservation",
    "managed_vitrines",
    "notifications",
    "projects",
    "public_demos",
    "public_ecommerce",
    "public_reservation",
    "secrets",
    "vitrine",
    "vitrine_auth",
]
