"""Routes HTTP — API CyberForge (generate, projects, managed-projects, health)."""

from fastapi import APIRouter

from api.routes import (
    agent_registry,
    agents_status,
    audit,
    clone_inspiration,
    clients,
    demos,
    generate,
    health,
    knowledge,
    llm_usage,
    llm_providers,
    memory,
    prompts_library,
    managed_application_web,
    managed_ecommerce,
    managed_extensions,
    managed_site_reservation,
    managed_vitrines,
    notifications,
    projects,
    scrape_inspiration,
    secrets,
    settings,
    system,
    tool_framework,
    workflows,
)

API_ROUTERS: list[tuple[APIRouter, str]] = [
    (health.router, "/api"),
    (agents_status.router, "/api"),
    (agent_registry.router, "/api"),
    (tool_framework.router, "/api"),
    (workflows.router, "/api"),
    (generate.router, "/api"),
    (projects.router, "/api"),
    (clients.router, "/api"),
    (knowledge.router, "/api"),
    (llm_usage.router, "/api"),
    (llm_providers.router, "/api"),
    (audit.router, "/api"),
    (prompts_library.router, "/api"),
    (memory.router, "/api"),
    (notifications.router, "/api"),
    (demos.router, "/api"),
    (secrets.router, "/api"),
    (settings.router, "/api"),
    (system.router, "/api"),
    (scrape_inspiration.router, "/api"),
    (clone_inspiration.router, "/api"),
    (managed_vitrines.router, "/api"),
    (managed_application_web.router, "/api"),
    (managed_ecommerce.router, "/api"),
    (managed_site_reservation.router, "/api"),
    (managed_extensions.router, "/api"),
]

__all__ = [
    "API_ROUTERS",
    "agent_registry",
    "agents_status",
    "clone_inspiration",
    "clients",
    "demos",
    "generate",
    "health",
    "audit",
    "knowledge",
    "llm_usage",
    "llm_providers",
    "memory",
    "prompts_library",
    "managed_application_web",
    "managed_ecommerce",
    "managed_extensions",
    "managed_site_reservation",
    "managed_vitrines",
    "notifications",
    "projects",
    "scrape_inspiration",
    "secrets",
    "settings",
    "system",
    "tool_framework",
    "workflows",
]
